name: sandbox_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #Calendar
  flutter_calendar_carousel: ^1.3.11

  #Home Timeline
  timeline: ^0.0.1
  timeline_list: ^0.0.3

  #Photo
  flutter_swiper : ^1.1.4
  photo_view: ^0.2.1

  #Multirequest Upload Image
  multipart_request: 

  #Firebase
  firebase_messaging: ^4.0.0+1
  firebase_core: ^0.2.5+1
  firebase_auth: ^0.6.2+1
  cloud_firestore: 
  google_sign_in: ^3.2.1
  firestore_ui: ^1.1.1

  #Geolocalización
  geocoder: ^0.1.2

  #URL External
  url_launcher: ^5.0.1

  #Request library
  http:

  #Map
  google_maps_flutter: ^0.3.0+2

  #Facebook Login
  flutter_facebook_login:

  #Camera
  ## camera: 
  ## path_provider:
  ## video_player:

  #Croper
  image_cropper: ^1.0.0

  #Image picker
  image_picker: 0.4.12+1
    
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #Redux
  flutter_redux: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
